### ISSUE TITLE
dark theme thunar windows white on white

### ISSUE THREAD

**Issue by AdrienLemaire** [Ferdi265/numix-solarized-gtk-theme#10]
Dark theme applied to Thunar results in white text shown on top of white background:

![2017-04-27_14-31-17](https://cloud.githubusercontent.com/assets/260983/25469304/6918f19a-2b56-11e7-9a0b-840b6e7eed60.png)

Note that the light theme works fine:
![2017-04-27_14-35-31](https://cloud.githubusercontent.com/assets/260983/25469375/cd8329c0-2b56-11e7-807f-9751ae01d19a.png)

Thunar uses GTK 2. I can actually easily reproduce the problem with `gtk-demo`:
![2017-04-27_15-04-17](https://cloud.githubusercontent.com/assets/260983/25470000/d80c9c2e-2b5a-11e7-95f1-ebddf5d07398.png)

**Comment by Ferdi265** [comment]
Thanks for the info. I don't use the dark theme much and I'm aware that some of it is broken.

I don't spend much time debugging and fixing stuff in these two themes as I have a lot of other stuff todo, but I'll be sure to fix this once I find time and figure out how
