### ISSUE TITLE
Add screenshots to README

### ISSUE THREAD

**Issue by jamesbvaughan** [Ferdi265/numix-solarized-gtk-theme#13]
A screenshot or two in the README would be immensly helpful for people who are interested in using this theme.

**Comment by Ferdi265** [comment]
I'll probably get to this soon, since I just started a README section specifically for Numix Solarized in front of the original README.

**Comment by Ferdi265** [comment]
Added two screenshots in c89f140. Community screenshots are always welcome though :)
