### ISSUE TITLE
Add installing Inkscape to installation instructions.

### ISSUE THREAD

**Issue by Elephantusparvus** [Ferdi265/numix-solarized-gtk-theme#15]
Inkscape needs to be installed otherwise the Makefile target "assets" fails, because the render-assets script makes use of Inkscape.
This results in an error similar to this https://github.com/numixproject/numix-gtk-theme/issues/582.

**Comment by Ferdi265** [comment]
Thanks, aware of the issue, but didn't see the readme had install instructions. In the ArchLinux PKGBUILD the dependencies were updated accordingly, but not here. Will do in a few days.

**Comment by Ferdi265** [comment]
Seems I haven't had time to do it until now, mostly because I haven't gotten around to writing an actual README.md for this project (instead of using Numix' README).

**Comment by Ferdi265** [comment]
fixed in 9d834cc with the new README.
