### ISSUE TITLE
Unable to install under Fedora 27

### ISSUE THREAD

**Issue by giulianisanches** [Ferdi265/numix-solarized-gtk-theme#21]
Hi,

I'm unable to install the Numix Solarized GTK Theme under Fedora 27 due to the following error:

```
glib-compile-resources --sourcedir=src/gtk-3.0 src/gtk-3.0/gtk.gresource.xml
src/gtk-3.0/gtk.gresource.xml: Failed to locate “assets/checkbox-checked-dark.png” in any source directory.
make: *** [Makefile:31: gresource] Error 1
```

All the required packages are installed (based on README.md instructions).

**Comment by Ferdi265** [comment]
Sorry, I didn't patch the README.md.

New build dependencies are `python3` and `inkscape`.
Build instructions are `make THEME=SolarizedLightGreen install` (or any of the other .colors files)

It looks a lot like the asset generation didn't work.
I'll try to clone fresh locally to double check that this isn't a problem with the repo.

EDIT: just checked, compiles for me with a fresh clone

**Comment by Ferdi265** [comment]
Can you provide me with a complete log from the Makefile?

Until then, I'll tag this with not-reproducible

**Comment by giulianisanches** [comment]
Hi, sorry for the late response.

After install Inkscape everything worked fine.

Thank you very much.
