### ISSUE TITLE
Tab colors for light theme

### ISSUE THREAD

**Issue by codesoverhill** [Ferdi265/numix-solarized-gtk-theme#22]
This is not an issue with this nice theme, but how to make terminal tabs to have light colors for lighter themes? I have tried xfce4-terminal, gnome-terminal/mate-terminal, roxterm. All have dark colors tabs. Thunar and other application's tabs, on the otherhand, are lighter.

**Comment by Ferdi265** [comment]
I have absolutely no idea. I'm not quite knowledgeable enough about GTK to fix that

**Comment by codesoverhill** [comment]
I will try to find out and post.
Thank you.

**Comment by AdrienLemaire** [comment]
@codesoverhill did you figure it out?
I'm also having trouble fixing my light theme
![](https://i.imgur.com/cAoBfsB.png)
