### ISSUE TITLE
Thank you for this project

### ISSUE THREAD

**Issue by 3ruce** [Ferdi265/numix-solarized-gtk-theme#23]
This is an amazing theme!

**Comment by Ferdi265** [comment]
Thank you :)

I don't really work actively on it, but i do merge numix upstream from time to time, so it should continue to work.

I don't really have time to work on DE integration (some of the theming there doesn't completely add up), but for DEs or WMs without much extra decoration (like e.g. i3) it works really well.

I appreciate this a lot. It's always nice to see people enjoy my theme :)

**Comment by 3ruce** [comment]
Yeah, it's a classic... I'm surprised the solarized themes aren't more popular to be honest, especially if you're using your machine for extended periods each day...

Dark or Light, it's great!

**Comment by Ferdi265** [comment]
Closed as WONTFIX
