### ISSUE TITLE
GTK3 scrollbars barely visible unless moused over when using any of the dark themes under XFCE.

### ISSUE THREAD

**Issue by mz1193** [Ferdi265/numix-solarized-gtk-theme#24]
Steps to reproduce: Choose any of the dark themes, open up a GTK3 application in XFCE.

I would suggest maybe changing the default appearance of the scrollbar to better match the GTK2 scrollbar, which is perfectly visible at all times.

**Comment by Ferdi265** [comment]
If you want you can try changing that, it's a one line change in the .colors files in the repository root. I currently don't have much time to maintain and test this theme, I mostly just periodically pull from upstream.

If you have a fix I'd merge it most likely.

**Comment by mz1193** [comment]
Thanks! I figured it out rather quickly. In the .colors files, change these lines:

@SCROLLBAR_SLIDER_COLOR_DARK@ shade(@BG_COLOR_DARK@, .5)
@SCROLLBAR_SLIDER_HOVER_COLOR_DARK@ shade(@BG_COLOR_DARK@, .3)

To these:

@SCROLLBAR_SLIDER_COLOR_DARK@ shade(@FG_COLOR_DARK@, .3)
@SCROLLBAR_SLIDER_HOVER_COLOR_DARK@ shade(@FG_COLOR_DARK@, .5)
