### ISSUE TITLE
Theme parsing error: gtk-dark.css:9381:21: Not using units is deprecated. Assuming 'px'.

### ISSUE THREAD

**Issue by Alexander-Shukaev** [Ferdi265/numix-solarized-gtk-theme#29]
Hi there, I see a lot of warning after system upgrade:

```
Theme parsing error: gtk-dark.css:9381:21: Not using units is deprecated. Assuming 'px'.
```

I think some styles need to be updated to include `px` where it's meant.  Thank you!

**Comment by Ferdi265** [comment]
This is an upstream bug of [numixproject/numix-gtk-theme](https://github.com/numixproject/numix-gtk-theme), please report the bug there. This project is only a patchset on top of Numix providing different color schemes.

Numix seems to be in "maintenance" mode, the project seems to only receive the most necessary bug fixes, which is probably why it contains uses of deprecated features.
